### ISSUE TITLE
Crude Express Middleware documentation improvement

### ISSUE THREAD

**Issue by ZsoltMaslanyi** [thanpolas/crude#14]
Hi @thanpolas , thanks for the great library!

Would be great to add to the Wiki that the proper way to use the Express type middleware feature is to instantiate Crude *without* providing the express instance, then adding the middleware and calling addRoutes.

Doing it with the express instance already passed on initialization doesn't work:

var userCrude = crude('/user', controller, expressApp);
userCrude.use(middleware);

But this way it does:

var userCrude = crude('/user', controller);
userCrude.use(middleware);
userCrude.addRoutes(expressApp);

What got me confused is that adding a query middleware after initializing with the express instance does work, so it took some time to figure out what might be wrong.

**Comment by thanpolas** [comment]
updated, thank you @ZsoltMaslanyi
